import { Button , VerticalBox, HorizontalBox, TextEdit, LineEdit} from "std-widgets.slint";
export component App inherits Window {
    width: 300px;
    height: 180px;
    title: "QRCode";
    in-out property <string> plate <=> p.text;
    in-out property <string> pclass <=> c.text;
    callback create-qr-code(string, string);
    VerticalBox {
        alignment: center;
        HorizontalBox {
            Text {
                font-size: 18px;
                text: "号牌号码:";
            }
            p:=LineEdit {
                font-size: 18px;
            }
        }
        HorizontalBox {
            Text {
                font-size: 18px;
                text: "号牌种类:";
            }
            c:=LineEdit {
                font-size: 18px;
            }
        }
        Button {
            text: "生成二维码";
            clicked => {
                root.create-qr-code(root.plate, root.pclass);
            }
        }
    }
}