[package]
name = "slint-demo"
version = "0.1.0"
edition = "2021"
build = "./ui/build.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slint = "*"

[build-dependencies]
slint-build = "*"
